//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IAddingUsers")]
    public interface IAddingUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddingUsers/AddUser", ReplyAction="http://tempuri.org/IAddingUsers/AddUserResponse")]
        void AddUser(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddingUsers/AddUser", ReplyAction="http://tempuri.org/IAddingUsers/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(long userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddingUsersChannel : ConsoleApplication1.ServiceReference2.IAddingUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddingUsersClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference2.IAddingUsers>, ConsoleApplication1.ServiceReference2.IAddingUsers {
        
        public AddingUsersClient() {
        }
        
        public AddingUsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddingUsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddingUsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddingUsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(long userId) {
            base.Channel.AddUser(userId);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(long userId) {
            return base.Channel.AddUserAsync(userId);
        }
    }
}
